=== sethkingsbury/my-truck/src/main/resources/data/testing/Cash.dtd
<!ENTITY version "V0.01 (C) Team 2 2019">
<!ELEMENT wad (description, (cash*))>
<!ELEMENT cash (type, denomination, valueInCents, initialQuantity)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT denomination (#PCDATA)>
<!ELEMENT valueInCents (#PCDATA)>
<!ELEMENT initialQuantity (#PCDATA)>
<!ELEMENT description (#PCDATA)>

=== sethkingsbury/my-truck/src/main/resources/data/filler/Cash.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE wad SYSTEM "Cash.dtd">
<wad>
    <description>List of cash denominations</description>
    <cash>
        <type>Coin</type>
        <denomination>10</denomination>
        <valueInCents>10</valueInCents>
        <initialQuantity>100</initialQuantity>
    </cash>
    <cash>
        <type>Coin</type>
        <denomination>20</denomination>
        <valueInCents>20</valueInCents>
        <initialQuantity>100</initialQuantity>
    </cash>
    <cash>
        <type>Coin</type>
        <denomination>50</denomination>
        <valueInCents>50</valueInCents>
        <initialQuantity>100</initialQuantity>
    </cash>
    <cash>
        <type>Coin</type>
        <denomination>1</denomination>
        <valueInCents>100</valueInCents>
        <initialQuantity>100</initialQuantity>
    </cash>
    <cash>
        <type>Coin</type>
        <denomination>2</denomination>
        <valueInCents>200</valueInCents>
        <initialQuantity>100</initialQuantity>
    </cash>
    <cash>
        <type>Note</type>
        <denomination>5</denomination>
        <valueInCents>500</valueInCents>
        <initialQuantity>100</initialQuantity>
    </cash>
    <cash>
        <type>Note</type>
        <denomination>10</denomination>
        <valueInCents>1000</valueInCents>
        <initialQuantity>100</initialQuantity>
    </cash>
    <cash>
        <type>Note</type>
        <denomination>20</denomination>
        <valueInCents>2000</valueInCents>
        <initialQuantity>100</initialQuantity>
    </cash>
    <cash>
        <type>Note</type>
        <denomination>50</denomination>
        <valueInCents>5000</valueInCents>
        <initialQuantity>100</initialQuantity>
    </cash>
    <cash>
        <type>Note</type>
        <denomination>100</denomination>
        <valueInCents>10000</valueInCents>
        <initialQuantity>100</initialQuantity>
    </cash>
</wad>
