=== sethkingsbury/my-truck/src/main/resources/data/testing/recipe.dtd
<!-- DTD for representing ingredients -->
<!-- (C) Neville Churcher 2019 -->
<!-- Note that the ingredient codes will need to
     match the corresponding entries in menus
-->
<!ENTITY version "V0.01 (C) Team 2 2019">
<!ELEMENT recipes (description, (recipe*))>
<!ELEMENT recipe (name, code, ingredients)>
<!ELEMENT ingredients (ingredient*)>
<!ELEMENT ingredient (code, amount)>
<!ELEMENT measurement (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT amount (#PCDATA)>
<!ELEMENT price (#PCDATA)>

=== sethkingsbury/my-truck/src/main/resources/data/testing/testRecipes.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE recipes SYSTEM "recipe.dtd">
<recipes>
	<description>List of Recipes</description>
	<recipe>
		<name>Beef Burger</name>
		<code>BBurger</code>
		<ingredients>
			<ingredient>
				<code>Salt</code>
				<amount>10</amount>
			</ingredient>
			<ingredient>
				<code>BBun</code>
				<amount>2</amount>
			</ingredient>
            <ingredient>
                <code>Cheese</code>
                <amount>2</amount>
            </ingredient>
            <ingredient>
                <code>BPat</code>
                <amount>1</amount>
            </ingredient>
		</ingredients>
	</recipe>
</recipes>

=== sethkingsbury/my-truck/src/main/resources/data/filler/Recipes.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE recipes SYSTEM "recipe.dtd">
<recipes>
	<description>List of Recipes</description>
	<recipe>
		<name>Beef Burger</name>
		<code>BBurger</code>
		<ingredients>
			<ingredient>
				<code>Salt</code>
				<amount>10</amount>
			</ingredient>
			<ingredient>
				<code>BBun</code>
				<amount>2</amount>
			</ingredient>
            <ingredient>
                <code>Cheese</code>
                <amount>2</amount>
            </ingredient>
            <ingredient>
                <code>BPat</code>
                <amount>1</amount>
            </ingredient>
		</ingredients>
	</recipe>
	<recipe>
		<name>Mushroom Chicken</name>
		<code>MushChick</code>
		<ingredients>
			<ingredient>
				<code>Shrooms</code>
				<amount>200</amount>
			</ingredient>
			<ingredient>
				<code>Chicken</code>
				<amount>400</amount>
			</ingredient>
			<ingredient>
				<code>milk</code>
				<amount>200</amount>
			</ingredient>
			<ingredient>
				<code>egg</code>
				<amount>2</amount>
			</ingredient>
			<ingredient>
				<code>Rice</code>
				<amount>200</amount>
			</ingredient>
		</ingredients>
	</recipe>
	<recipe>
		<name>Pancakes</name>
		<code>pancakes</code>
		<ingredients>
			<ingredient>
				<code>milk</code>
				<amount>200</amount>
			</ingredient>
			<ingredient>
				<code>egg</code>
				<amount>2</amount>
			</ingredient>
			<ingredient>
				<code>butter</code>
				<amount>200</amount>
			</ingredient>
			<ingredient>
				<code>gsyrup</code>
				<amount>30</amount>
			</ingredient>
		</ingredients>
	</recipe>
	<recipe>
		<name>Toast</name>
		<code>toast</code>
		<ingredients>
			<ingredient>
				<code>bread</code>
				<amount>2</amount>
			</ingredient>
			<ingredient>
				<code>peanutbutter</code>
				<amount>50</amount>
			</ingredient>
		</ingredients>
	</recipe>
	<recipe>
		<name>Vegetable Soup</name>
		<code>vegesoup</code>
		<ingredients>
			<ingredient>
				<code>Salt</code>
				<amount>1</amount>
			</ingredient>
			<ingredient>
				<code>BBun</code>
				<amount>2</amount>
			</ingredient>
			<ingredient>
				<code>Cheese</code>
				<amount>200</amount>
			</ingredient>
			<ingredient>
				<code>BPat</code>
				<amount>1</amount>
			</ingredient>
		</ingredients>
	</recipe>
	<recipe>
		<name>Chocolate Ice-cream</name>
		<code>chocicecream</code>
		<ingredients>
			<ingredient>
				<code>Salt</code>
				<amount>1</amount>
			</ingredient>
			<ingredient>
				<code>BBun</code>
				<amount>2</amount>
			</ingredient>
			<ingredient>
				<code>Cheese</code>
				<amount>200</amount>
			</ingredient>
			<ingredient>
				<code>BPat</code>
				<amount>1</amount>
			</ingredient>
		</ingredients>
	</recipe>
	<recipe>
		<name>Apple Pie</name>
		<code>applepie</code>
		<ingredients>
			<ingredient>
				<code>Salt</code>
				<amount>1</amount>
			</ingredient>
			<ingredient>
				<code>BBun</code>
				<amount>2</amount>
			</ingredient>
			<ingredient>
				<code>Cheese</code>
				<amount>200</amount>
			</ingredient>
			<ingredient>
				<code>BPat</code>
				<amount>1</amount>
			</ingredient>
		</ingredients>
	</recipe>
</recipes>
