=== sethkingsbury/my-truck/src/main/resources/data/testing/user.dtd
<!ENTITY version "V0.01 (C) Team 2 2019">
<!ELEMENT description (#PCDATA)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ATTLIST user
        accountType (0|1|2|3) "0"
        >
<!ELEMENT user (username, password)>
<!ELEMENT users (description, (user*))>

=== sethkingsbury/my-truck/src/main/resources/data/filler/Users.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE users SYSTEM "user.dtd">
<users>
    <description>List of users</description>
    <user accountType="1">
        <username>andyanlyst</username>
        <password>admin</password>
    </user>
    <user accountType="2">
        <username>managermandy</username>
        <password>admin</password>
    </user>
    <user>
        <username>salessteve</username>
        <password>user</password>
    </user>
    <user accountType="3">
        <username>ownerbob</username>
        <password>owner</password>
    </user>
</users>
