=== sethkingsbury/my-truck/src/main/resources/data/filler/supplier.dtd
<!-- DTD for representing ingredients -->
<!-- (C) Neville Churcher 2019 -->
<!-- Note that the ingredient codes will need to
     match the corresponding entries in menus
-->
<!ENTITY version "V0.01 (C) Team 2 2019">
<!ELEMENT suppliers (description, (supplier*))>
<!ELEMENT supplier (contact, name)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT contact (#PCDATA)>

=== sethkingsbury/my-truck/src/main/resources/data/filler/Suppliers.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE suppliers SYSTEM "supplier.dtd">
<suppliers>
    <description>List of suppliers</description>
    <supplier>
        <contact>0220132253</contact>
        <name>Shivin Gaba</name>
    </supplier>
    <supplier>
        <contact>0215559921</contact>
        <name>Harry Collard</name>
    </supplier>
</suppliers>
